--- #YAML:1.0
name:               Yahoo-Weather
version:            0.04
abstract:           Perl extension to Find Current Observation WEATHER  and Two Day Forecast for  a given Location or ZIP CODE.
author:
    - Krishna Chaitanya Averineni <kchaitan@apple.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::Simple:  5.835
    Test::More:   0.86
    XML::Simple:  2.14
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
